name: learn-github-actions.yaml
run-name: ${{ github.actor }} is learning Github Actions
on: [push]
jobs: 
  check-bats-version:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: npm bets -v
